version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: jarvistrade_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-your_secure_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-jarvistrade_prod}
      MYSQL_USER: ${MYSQL_USER:-jarvistrade_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-your_secure_password}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_SQL_MODE: STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql
    networks:
      - jarvistrade_network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=256M
      --innodb-flush-log-at-trx-commit=2
      --innodb-flush-method=O_DIRECT
      --max-connections=200
      --query-cache-size=64M
      --query-cache-type=1
      --tmp-table-size=64M
      --max-heap-table-size=64M
      --table-open-cache=2000
      --thread-cache-size=16
      --key-buffer-size=128M
      --sort-buffer-size=2M
      --read-buffer-size=2M
      --read-rnd-buffer-size=8M
      --myisam-sort-buffer-size=8M
      --thread-concurrency=8
      --innodb-thread-concurrency=0
      --innodb-read-io-threads=4
      --innodb-write-io-threads=4
      --innodb-io-capacity=200
      --innodb-io-capacity-max=400
      --innodb-lru-scan-depth=1024
      --innodb-adaptive-hash-index=1
      --innodb-change-buffering=all
      --innodb-buffer-pool-instances=1
      --innodb-file-per-table=1
      --innodb-open-files=400
      --innodb-stats-on-metadata=0
      --innodb-buffer-pool-dump-at-shutdown=1
      --innodb-buffer-pool-load-at-startup=1
      --innodb-log-buffer-size=64M
      --innodb-log-files-in-group=2
      --innodb-autoinc-lock-mode=2
      --innodb-lock-wait-timeout=50
      --innodb-rollback-on-timeout=0
      --innodb-print-all-deadlocks=1
      --innodb-deadlock-detect=1
      --innodb-status-file=1
      --log-error=/var/log/mysql/error.log
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2
      --log-queries-not-using-indexes=1
      --log-slow-admin-statements=1
      --log-slow-slave-statements=1
      --log-bin=/var/log/mysql/mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
      --expire-logs-days=7
      --max-binlog-size=100M
      --sync-binlog=1
      --server-id=1
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-slave-updates=ON
      --binlog-checksum=NONE
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD:-your_secure_root_password}",
        ]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: jarvistrade_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - jarvistrade_network
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5
      interval: 10s

  app:
    build: .
    container_name: jarvistrade_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-jarvistrade_user}:${MYSQL_PASSWORD:-your_secure_password}@mysql:3306/${MYSQL_DATABASE:-jarvistrade_prod}
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./digital_products:/app/digital_products
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - jarvistrade_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: jarvistrade_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - jarvistrade_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      timeout: 10s
      retries: 5
      interval: 30s

volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
  redis_data:
    driver: local

networks:
  jarvistrade_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
