"""Initial migration

Revision ID: e6e8445173d8
Revises: 
Create Date: 2025-08-18 10:45:34.317895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e8445173d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_messages_created_at', table_name='project_messages')
    op.drop_index('idx_project_messages_project_id', table_name='project_messages')
    op.drop_index('idx_project_messages_sender_id', table_name='project_messages')
    op.drop_table('project_messages')
    op.drop_index('idx_blog_comments_approved', table_name='blog_comments')
    op.drop_index('idx_blog_comments_parent_id', table_name='blog_comments')
    op.drop_index('idx_blog_comments_post_id', table_name='blog_comments')
    op.drop_index('idx_blog_comments_user_id', table_name='blog_comments')
    op.drop_index('idx_blog_likes_post_id', table_name='blog_likes')
    op.drop_index('idx_blog_likes_user_id', table_name='blog_likes')
    op.alter_column('blog_posts', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('blog_posts', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('blog_posts', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('blog_posts', 'excerpt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('blog_posts', 'featured_image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'author_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('blog_posts', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('blog_posts', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('blog_posts', 'meta_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'meta_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('blog_posts', 'like_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('blog_posts', 'comment_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_blog_posts_author', table_name='blog_posts')
    op.drop_index('idx_blog_posts_featured', table_name='blog_posts')
    op.drop_index('idx_blog_posts_published', table_name='blog_posts')
    op.drop_index('idx_blog_posts_slug', table_name='blog_posts')
    op.drop_index('idx_blog_posts_status', table_name='blog_posts')
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_posts_title'), 'blog_posts', ['title'], unique=False)
    op.alter_column('download_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('download_logs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_logs', 'product_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_logs', 'license_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_logs', 'download_token_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_logs', 'ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_logs', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_logs', 'download_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('download_logs', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('download_logs', 'download_status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_logs', 'success',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('download_logs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_tokens', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('download_tokens', 'download_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('download_tokens', 'max_downloads',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('exchange_rates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('exchange_rates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('licenses', 'is_rental',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_licenses_license_id', table_name='licenses')
    op.drop_index('idx_licenses_user_product', table_name='licenses')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_is_read', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.alter_column('order_items', 'is_rental',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'original_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('products', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'youtube_demo_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'test_download_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'max_activations',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'version',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'platform',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'has_rental_option',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'rental_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('products', 'rental_duration_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_products_platform', table_name='products')
    op.drop_index('idx_products_slug', table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.alter_column('project_invoices', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_project_invoices_number', table_name='project_invoices')
    op.drop_index('idx_project_invoices_request_id', table_name='project_invoices')
    op.drop_index('idx_project_progress_request_id', table_name='project_progress')
    op.alter_column('project_responses', 'parent_response_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_project_responses_request_id', table_name='project_responses')
    op.drop_index('idx_reviews_created_at', table_name='reviews')
    op.drop_index('idx_reviews_product_id', table_name='reviews')
    op.drop_index('idx_reviews_user_id', table_name='reviews')
    op.alter_column('user_product_activations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user_product_activations', 'license_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('user_product_activations', 'account_login',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('user_product_activations', 'account_server',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('user_product_activations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_product_activations', 'activated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user_product_activations', 'deactivated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user_product_activations', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_activations_account', table_name='user_product_activations')
    op.drop_index('idx_activations_license', table_name='user_product_activations')
    op.alter_column('users', 'country',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'currency',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'currency_symbol',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'notification_preferences',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'push_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'push_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(TRUE)'),
               existing_nullable=True)
    op.alter_column('users', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(TRUE)'),
               existing_nullable=True)
    op.alter_column('users', 'notification_preferences',
               existing_type=sa.TEXT(),
               server_default=sa.text('\'{"info": true, "success": true, "warning": true, "error": true, "payment": true, "order": true, "system": true, "update": true, "review_prompt": true}\''),
               existing_nullable=True)
    op.alter_column('users', 'currency_symbol',
               existing_type=sa.String(),
               server_default=sa.text("'$'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'currency',
               existing_type=sa.String(),
               server_default=sa.text("'USD'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.String(),
               server_default=sa.text("'US'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_activations_license', 'user_product_activations', ['license_id'], unique=False)
    op.create_index('idx_activations_account', 'user_product_activations', ['account_login', 'account_server'], unique=False)
    op.alter_column('user_product_activations', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_product_activations', 'deactivated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_product_activations', 'activated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_product_activations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('user_product_activations', 'account_server',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('user_product_activations', 'account_login',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('user_product_activations', 'license_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('user_product_activations', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_index('idx_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_index('idx_reviews_product_id', 'reviews', ['product_id'], unique=False)
    op.create_index('idx_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('idx_project_responses_request_id', 'project_responses', ['project_request_id'], unique=False)
    op.alter_column('project_responses', 'parent_response_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_project_progress_request_id', 'project_progress', ['project_request_id'], unique=False)
    op.create_index('idx_project_invoices_request_id', 'project_invoices', ['project_request_id'], unique=False)
    op.create_index('idx_project_invoices_number', 'project_invoices', ['invoice_number'], unique=False)
    op.alter_column('project_invoices', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index('idx_products_slug', 'products', ['slug'], unique=False)
    op.create_index('idx_products_platform', 'products', ['platform'], unique=False)
    op.alter_column('products', 'rental_duration_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(30)'),
               existing_nullable=True)
    op.alter_column('products', 'rental_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('products', 'has_rental_option',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('products', 'platform',
               existing_type=sa.String(),
               server_default=sa.text("'MT4'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'version',
               existing_type=sa.String(),
               server_default=sa.text("'1.0.0'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'max_activations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('products', 'test_download_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'youtube_demo_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('products', 'original_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('order_items', 'is_rental',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_licenses_user_product', 'licenses', ['user_id', 'product_id'], unique=False)
    op.create_index('idx_licenses_license_id', 'licenses', ['license_id'], unique=False)
    op.alter_column('licenses', 'is_rental',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('exchange_rates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('exchange_rates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('download_tokens', 'max_downloads',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('download_tokens', 'download_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('download_tokens', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'success',
               existing_type=sa.Boolean(),
               server_default=sa.text('1'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('download_logs', 'download_status',
               existing_type=sa.String(),
               server_default=sa.text("'success'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'download_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'ip_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'download_token_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'license_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'product_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('download_logs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_blog_posts_title'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.create_index('idx_blog_posts_status', 'blog_posts', ['status'], unique=False)
    op.create_index('idx_blog_posts_slug', 'blog_posts', ['slug'], unique=False)
    op.create_index('idx_blog_posts_published', 'blog_posts', ['published_at'], unique=False)
    op.create_index('idx_blog_posts_featured', 'blog_posts', ['is_featured'], unique=False)
    op.create_index('idx_blog_posts_author', 'blog_posts', ['author_id'], unique=False)
    op.alter_column('blog_posts', 'comment_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('blog_posts', 'like_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.alter_column('blog_posts', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.alter_column('blog_posts', 'meta_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'meta_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('blog_posts', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('blog_posts', 'status',
               existing_type=sa.String(),
               server_default=sa.text("'draft'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'author_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('blog_posts', 'featured_image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'excerpt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('blog_posts', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('blog_posts', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('blog_posts', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_index('idx_blog_likes_user_id', 'blog_likes', ['user_id'], unique=False)
    op.create_index('idx_blog_likes_post_id', 'blog_likes', ['blog_post_id'], unique=False)
    op.create_index('idx_blog_comments_user_id', 'blog_comments', ['user_id'], unique=False)
    op.create_index('idx_blog_comments_post_id', 'blog_comments', ['blog_post_id'], unique=False)
    op.create_index('idx_blog_comments_parent_id', 'blog_comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_blog_comments_approved', 'blog_comments', ['is_approved'], unique=False)
    op.create_table('project_messages',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_request_id', sa.VARCHAR(), nullable=False),
    sa.Column('sender_id', sa.VARCHAR(), nullable=False),
    sa.Column('sender_type', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_request_id'], ['project_requests.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_messages_sender_id', 'project_messages', ['sender_id'], unique=False)
    op.create_index('idx_project_messages_project_id', 'project_messages', ['project_request_id'], unique=False)
    op.create_index('idx_project_messages_created_at', 'project_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###

